# Github Actions: Mytime Production Deploy
name: Nginx compiling

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

concurrency: production

jobs:
  depot-build:
    name: run docker container from Dockerfile with nginx compiling instructions
    runs-on: ubuntu-latest
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - name: Get lowercase repository name
        run: |
          echo "GH_LWREPONAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: depot/build-push-action@v1
        with:
          project: 0rt4j1j1hh
          tags: ghcr.io/${{ env.GH_LWREPONAME }}:1.24.0-${{ github.run_number }}
          push: true
    - name: Telegram notify
      run: |
        cat <<- EOF | /usr/bin/curl -s -XPOST "https://api.telegram.org/${{ secrets.TGRM_BOT_SECRET }}/sendMessage" \
          -d chat_id="${{ secrets.TGRM_CHAT_ID }}" -d text="$(cat /dev/stdin)" &>/dev/null
        Nginx Builder (Github Actions)

        Build ${{ github.run_number }} of job ${{ github.workflow }} has been completed.
        Builded commit: ${{ github.sha }}
        EOF