# Github Actions: Mytime Production Deploy
name: Nginx compiling

on:
  push:
    branches: [ "*" ]

jobs:
  nginx_build:
    name: run docker container from Dockerfile with nginx compiling instructions
    runs-on: ubuntu-latest
    steps:
    - name: Get Mytime-Dockerfiles repo
      uses: actions/checkout@v2
      with:
        path: docker-nginx
        submodules: recursive
    # here we trying to use NEW github cache backend - https://github.com/docker/buildx/pull/535
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.6.0-rc1
        driver-opts: image=moby/buildkit:v0.9.0-rc2,network=host
        buildkitd-flags: --debug
    - name: MindHunter's registry login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URI }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Build and export nginx image
      uses: docker/build-push-action@v2
      with:
        push: true
        pull: false
        context: docker-nginx/
        tags: ${{ secrets.DOCKER_REGISTRY_URI }}/nginx:1.24.0-${{ github.run_number }}
        cache-from: type=gha
        cache-to: type=gha/
    - name: Telegram notify
      run: |
        cat <<- EOF | /usr/bin/curl -s -XPOST "https://api.telegram.org/${{ secrets.TGRM_BOT_SECRET }}/sendMessage" \
          -d chat_id="${{ secrets.TGRM_CHAT_ID }}" -d text="$(cat /dev/stdin)" &>/dev/null
        Nginx Builder (Github Actions)

        Build ${{ github.run_number }} of job ${{ github.workflow }} has been completed.
        Builded commit: ${{ github.sha }}
        EOF
