# Github Actions: Salt Master data deploy
name: Salt Master pillar deploy

on:
  push:
    branches: [ "master" ]

jobs:
  salt_data_deploy:
    name: Deploy salt data on masters
    runs-on: ubuntu-latest
    steps:
    - name: Export SSH pem key for tunnel building
      run: |
        umask 0077
        cat <<-EOF > private.pem
        ${{ secrets.SMASTER_SSH_PEM }}
        EOF
    - name: Building SSH tunnel to Salt Master host
      run: |
        ssh \
          -o ServerAliveCountMax=6 \
          -o ServerAliveInterval=10 \
          -o PreferredAuthentications=publickey \
          -o StrictHostKeyChecking=no \
          -NL 30873:localhost:873 \
          -i private.pem ${{ secrets.SMASTER_SSH_HOSTARGS }} &
    - name: Get Salt pillar
      uses: actions/checkout@v2
      with:
        path: pillar
        submodules: recursive
    - name: Sync all Salt data to Salt Master host over encrypted tunnel
      run: |
        rsync -aAxXv --numeric-ids --chown='root:root' --exclude='.git*' --progress --delete pillar rsync://localhost:30873/salt_master_data/
    - name: Drop established encrypted tunnel
      run: |
        jobs -p | xargs -n1 | xargs -ri kill {}
    - name: Telegram notify
      run: |
        cat <<- EOF | /usr/bin/curl -s -XPOST "https://api.telegram.org/${{ secrets.TGRM_BOT_SECRET }}/sendMessage" \
          -d chat_id="${{ secrets.TGRM_CHAT_ID }}" -d text="$(cat /dev/stdin)" &>/dev/null
        GitHub Actions Builder

        Build ${{ github.run_number }} of job ${{ github.workflow }} has been completed.
        Builded commit: ${{ github.sha }}
        EOF
